# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: expert_images_app_development
  username: postgres
  password: "1234"
  host: localhost
  port: 5432

test:
  <<: *default
  database: expert_images_app_test
  username: postgres
  password: "1234"
  host: localhost
  port: 5432
#
production:
  primary: &primary_production
    <<: *default
    database: expert_images_app_production
    username: expert_images_app
    password: <%= ENV["EXPERT_IMAGES_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: expert_images_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: expert_images_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: expert_images_app_production_cable
    migrations_paths: db/cable_migrate
